### ISSUE TITLE
Bitcode enabled SDK version

### ISSUE THREAD

**Issue by michaelkamphausen** [computop/Computop-iOS#5]
We are maintaining a large iOS app and successfully invested some time to compile it together with all it's dependencies as Bitcode to significantly reduce the app's size.
Unfortunately, I cannot find a version of your framework built with Bitcode enabled, so we cannot ship our app with your SDK.
Could you please provide an additional build with Bitcode enabled?

**Comment by geraldcollaku** [comment]
The version with Bitcode enabled is released on cocoapods (Computop 1.2.1)

**Comment by michaelkamphausen** [comment]
Great. Thank you!
