### ISSUE TITLE
Cannot pay with PayPal anymore

### ISSUE THREAD

**Issue by michaelkamphausen** [computop/Computop-iOS#7]
I updated the Computop SDK in our app project to the latest version published 4 days ago. Since then, payment via PayPal is no longer possible.
Your WebView stays blank and some kind of very long query string is displayed in a tiny font.

**Comment by geraldcollaku** [comment]
Paypal is different from other methods, where you show the CheckoutViewController. Here we show  the SafariViewController and then we redirect to our app after the payment is canceled/successful.
Please read the documentation for implementing the PayPal payment and add correctly the parameters URLSuccess & URLFailure. Also register the URL scheme to your merchant server and to your app.

**Comment by michaelkamphausen** [comment]
The new PayPal Checkout using CMPayPal does not work either.
The PayPal website in SFSafariViewController reports an error saying that the transaction has expired right from the beginning before the user even had a chance to login with his PayPal credentials.
Why? Has anything else changed? Is there a way to get an error message or hint what went wrong under the hood?

**Comment by michaelkamphausen** [comment]
Any update on this?
